version: "3.9"

networks:
    default:
        name: ft_transcendence
services:
  postgres:
      image: postgres
      env_file:
        - ./docker/postgres.env
      ports:
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: on-failure

  # server:
  #     build: ./server
  #     ports:
  #       - 3000:3000
  #     env_file:
  #       - ./docker/server.env
  #     depends_on:
  #       - postgres
  #     restart: on-failure

  # client:
  #     build: ./front
  #     ports:
  #       - 4200:4200
  #     depends_on:
  #       - server
  #       - postgres
  #     restart: on-failure

volumes:
    postgres_data: