version: "3.9"

networks:
    default:
        name: ft_transcendence
services:
  postgres:
      image: postgres:latest
      env_file:
        - ./docker/postgres.env
      ports:
        - 5432:5432
      restart: unless-stopped

  # server:
  #     build: ./server
  #     ports:
  #       - 3000:3000
  #     env_file:
  #       - ./server/.env
  #     depends_on:
  #       - postgres
  #     restart: unless-stopped

  # client:
  #     build: ./front
  #     ports:
  #       - 4200:4200
  #     depends_on:
  #       - server
  #     restart: unless-stopped
  #     volumes: 
  #       - ./front:./app
  #       - /app/node_modules

# volumes:
#     postgres_data:
#         driver: local
#         driver_opts:
#             o: "bind"
#             type: "none"
#             device: "/goinfre/eabdelha/docker/Volumes"